

services:
  backend:
    container_name: backend-prove2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: myappdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: