

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  backend:
    build: .
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/myappdb?authSource=admin
      ACCESS_TOKEN_SECRET: admin1
      ACCESS_TOKEN_EXPIRATION: 1h
      REFRESH_TOKEN_SECRET: admin2
      REFRESH_TOKEN_EXPIRATION: 7d